services:
  db:
    image: mysql:8.0
    container_name: travelmanagement-db
    restart: always
    environment:
      MYSQL_DATABASE: travelmanagement
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - travel-net

  backend:
    build:
      context: ../travel-backend
      dockerfile: ../docker_files/Dockerfile.backend
    container_name: travelmanagement-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/travelmanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8082
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - travel-net


volumes:
  db_data:

networks:
  travel-net:
    driver: bridge
